### ISSUE TITLE
Cannot find the setter for attribute 'app:animate'

### ISSUE THREAD

**Issue by Divya1903** [Ekalips/ExpandableCardViewList#2]
Hey, I have followed all the steps described in implementation of data binding for expandablecardview,  but for some reason my gradle build fails with the following stack trace.

```
****/ data binding error ****msg:Cannot find the setter for attribute 'app:animate' with parameter type boolean on android.widget.ImageView.
  file:F:\Behtar Projects\Venus\app\src\main\res\layout\faq_item.xml
  loc:78:35 - 78:49
  ****\ data binding error ****
```

I have searched for a solution for hours related to my use-case, but cannot find anything working.

**Comment by Ekalips** [comment]
Hello @Divya1903 
Seems like you didn't copy custom binders located here: `ExpandableCardViewList/app/src/main/java/com/wldev/expandablecardviewlist/bindings/Bindings.java`

**Comment by Divya1903** [comment]
> Hello @Divya1903
> Seems like you didn't copy custom binders located here: `ExpandableCardViewList/app/src/main/java/com/wldev/expandablecardviewlist/bindings/Bindings.java`

I did it too. and in the same way as you did.

**Comment by Ekalips** [comment]
Does you `faq_layout` matches my `rv_item`? 
I'm interested in view that has `app:animate` property.  

That view has to have 3 properties in order to be valid: app:animate, app:animation, app: fastAnimation

**Comment by Divya1903** [comment]
Actually I am using different fields, namely, question and answer in my `faq_item`,you being using title and description in your `rv_item`, but I have placed attributes in `Imageview `exactly like you did in your code. I also did clone your project and it ran perfectly without any errors or crashes. But gradle fails in my code every time.

One thing I forgot to mention is that I am using androidx dependencies in my project but as I went through your example, you are using support libraries.  Could androidx be the cause of my issue?

**Comment by Ekalips** [comment]
I don't think that androidx will cause any problems here. 
And I don't really know what's goin wrong with your build. You can upload your stuff into git (for example, fork my project, upload your changes, push it and give me a link)

**Comment by Divya1903** [comment]
I have forked your project and pushed my changes in my repo. Please have a look at it.
[Forked repo link](https://github.com/Divya1903/ExpandableCardViewList)

**Comment by Ekalips** [comment]
You've missed one property on that ImageView 

Here's your ImageView:
```
                <ImageView
                    android:id="@+id/arrow_faq_iv"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:contentDescription="@string/arrow_icon"
                    android:src="@drawable/ic_arrow_down"
                    app:animate="@{!state.expanded}"
                    app:animation="@{@anim/scale_anim}"
                    app:fastReverse="@{state.fast}"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    app:reverse="@{state.expanded}"
                    app:reverseAnimation="@{@anim/scale_anim_reverse}" />
```

And here how it should be:
```
                <ImageView
                    android:id="@+id/arrow_faq_iv"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:contentDescription="@string/arrow_icon"
                    android:src="@drawable/ic_arrow_down"
                    app:animate="@{!state.expanded}"
                    app:animation="@{@anim/scale_anim}"
                    app:fastAnimation="@{state.fast}"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    app:reverse="@{state.expanded}"
                    app:fastReverse="@{state.fast}"
                    app:reverseAnimation="@{@anim/scale_anim_reverse}" />
```

**Comment by Divya1903** [comment]
Gradle built successfully this time!!.. Was a really silly mistake..Didn't notice that I guess because of the same property value in both `fastAnimation` and `reverse` attribute.
